# To build and launch (first time):
#   $ docker-compose up -d
# To create new images (--no-cache) to force building from scratch:
#   $ docker-compose build
# To launch again (leave out -d for non daemon launch):
#   $ docker-compose up -d
# Short command for rebuilding and restarting
#   $ docker-compose up -d --build
# To stop containers:
#  $ docker-compose stop
# To clean up containers/images/networks:
#  $ docker system prune
version: '3'
networks:
  frontend:
    driver: bridge
  database:
    driver: bridge
services:
  nginx:
    build:
      context: .
      dockerfile: "Dockerfile.nginx.dev"
    depends_on:
      - studio
    volumes:
      - ssl:/ssl_certs
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
  studio:
    build:
      context: .
      dockerfile: "Dockerfile.studio"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=docker
    volumes:
      - ssl:/webgmeshare/ssl_certs
      - work:/webgmeshare/work_temp
      - keys:/webgmeshare/token_keys
      - blob:/webgmeshare/blob-local-storage
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/usr/app/config/
    networks:
      - database
      - frontend
  mongo:
    image: mongo:3.4.1
    volumes:
      - db:/data/db
    networks:
      - database
volumes:
  db:
  ssl:
  work:
  keys:
  blob: