// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.visualization.layout.basePaths.push(__dirname + '/../src/layouts');
config.visualization.decoratorPaths.push(__dirname + '/../node_modules/ui-components/src/decorators');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/SpaceEx');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/HySTBase');



config.visualization.panelPaths.push(__dirname + '/../src/visualizers/panels');


config.rest.components['HyST'] = {
  src: __dirname + '/../src/routers/HyST/HyST.js',
  mount: 'routers/HyST',
  options: {}
};

// Visualizer descriptors
config.visualization.visualizerDescriptors.push(__dirname + '/../src/visualizers/Visualizers.json');
// Add requirejs paths
config.requirejsPaths = {
  'MultilineAttributeDecorator': 'node_modules/ui-components/src/decorators/MultilineAttributeDecorator',
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets',
  'ui-components': './node_modules/ui-components/src/common',
  'hysteditor': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/hysteditor';
validateConfig(config);
module.exports = config;
